site_name: Atlas Control
site_url: https://altasflight.github.io/atlas-docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: lime
      toggle:
        icon: material/weather-night
        name: Увімкнути темну тему
    - scheme: slate
      primary: custom
      accent: lime


      toggle:
        icon: material/weather-sunny
        name: Увімкнути світлу тему
  font:
    text: Roboto Mono
  custom_dir: overrides

extra_css:
  - extra.css

nav:
  - Опис: index.md
  - Налаштування FC: setting.md
  - Комплектація: FCkit.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true